steps:
- name: gcr.io/cloud-builders/gsutil
  args: ['rsync', '-r', '-x', '"\.git.*|setup.sh|README.md"', '.', 'gs://sapdeployment/']
- name: gcr.io/cloud-builders/gsutil
  args: ['-D', 'setacl', '-r', 'public-read', 'gs://sapdeployment/*']
- name: gcr.io/cloud-builders/gsutil
  args: ['setmeta', '-h', 'cache-control:private, max-age=0, no-transform', 'gs://sapdeployment/*/*']
- name: gcr.io/cloud-builders/gsutil
  args: ['setmeta', '-h', 'cache-control:private, max-age=0, no-transform', 'gs://sapdeployment/*']